no longer calls pip3 install if compilation of GP-GOMEA fails

diff --git a/m_fedora b/m_fedora
--- a/m_fedora
+++ b/m_fedora
@@ -21,6 +21,12 @@ dnf install boost-python3-devel
 # compile the c++ project
 echo ">>> Compiling GP-GOMEA source code..."
 make
+if [ $? -eq 0 ]; then
+    echo ">>> GP-GOMEA compilation successful"
+else
+    echo ">>> GP-GOMEA compilation FAILED, see log above"
+    exit 1
+fi
 
 # copy the .so library into the python package
 cp dist/Python_Release/GNU-Linux/gpgomea pyGPGOMEA/gpgomea.so
